greeting: "Hello"

---

spring:
    profiles: stage

greeting: "This is STAGE server."

---

spring:
    profiles: dev

greeting: "This is DEV server modified."

---

spring:
    profiles: local

greeting: "This is LOCAL server."
